"""Generates the launchpad catalog import migration from the admin export JSON.

Kept in the repo so the migration's contents are reproducible and reviewable.
Usage: python3 scripts/generate-launchpad-import-migration.py <export.json> <migration.sql>
"""
import json
import sys

STATUS_MAP = {"LIVE": "live", "BETA": "beta", "COMING_SOON": "coming-soon", "INTERNAL": "internal", "ARCHIVED": "archived"}
LAUNCHPAD_EXTRA_KEYS = ["id", "tagline", "iconLetter", "audiences", "benefits", "features", "accessType", "published", "pricingType", "supportUrl", "faqs"]


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def catalog_entry(program: dict) -> dict:
    tagline = (program.get("tagline") or "").strip()
    short = (program.get("shortDescription") or "").strip() or tagline
    long = (program.get("fullDescription") or "").strip() or short
    status = STATUS_MAP.get(program.get("status", ""), "live")
    return {
        "shortDescription": short,
        "longDescription": long,
        "category": program.get("category") or "Productivity",
        "secondaryCategory": "",
        "tags": program.get("tags") or [],
        "status": status,
        "type": "external",
        "origin": "suite-native",
        "externalUrl": program.get("launchUrl") or "",
        "openInNewTab": True,
        "logoUrl": "",
        "screenshotUrl": "",
        "accentColor": program.get("accentColor") or "",
        "adminOnly": False,
        "isFeatured": bool(program.get("featured")),
        "isPublic": program.get("accessType", "PUBLIC") == "PUBLIC" and bool(program.get("published", True)),
        "requiresLogin": False,
        "requiresApproval": False,
        "launchLabel": "Launch Program",
        "displayOrder": int(program.get("displayOrder") or 100),
        "notes": "Imported from the NXT LVL launchpad admin export (2026-10-07).",
    }


def main(source: str, target: str) -> None:
    programs = json.load(open(source))["custom"]
    rows = []
    for program in programs:
        settings = {
            "catalog": catalog_entry(program),
            "launchpad": {key: program.get(key) for key in LAUNCHPAD_EXTRA_KEYS if key in program},
        }
        api_status = "archived" if settings["catalog"]["status"] == "archived" else "active"
        rows.append(
            "    ({id}, {name}, {slug}, '{status}'::\"ProgramStatus\", {settings}::jsonb)".format(
                id=sql_literal("suite-" + program["slug"]),
                name=sql_literal(program["name"]),
                slug=sql_literal(program["slug"]),
                status=api_status,
                settings=sql_literal(json.dumps(settings, ensure_ascii=False, sort_keys=True)),
            )
        )

    sql = f"""-- Imports the {len(programs)} programs from the NXT LVL launchpad admin export (2026-10-07)
-- into the hub catalog (Program.type = suite_app, owned by the 'nxt-lvl' organization).
-- Insert-only: existing rows are never modified. If a slug is already taken in that organization,
-- the program is imported as '<slug>-suite' instead (so no program is lost) and a WARNING is logged.
-- Re-running is a no-op because rows are keyed by their deterministic ids. Generated by
-- scripts/generate-launchpad-import-migration.py from prisma/data/launchpad-programs-export-2026-10-07.json.
DO $$
DECLARE
  org_id TEXT;
  entry RECORD;
  target_slug TEXT;
BEGIN
  SELECT "id" INTO org_id FROM "Organization" WHERE "slug" = 'nxt-lvl' ORDER BY "createdAt" LIMIT 1;
  IF org_id IS NULL THEN
    RAISE WARNING 'suite catalog import skipped: organization nxt-lvl not found';
    RETURN;
  END IF;

  FOR entry IN
    SELECT * FROM (VALUES
{(","+chr(10)).join(rows)}
    ) AS v("id", "name", "slug", "status", "settings")
  LOOP
    CONTINUE WHEN EXISTS (SELECT 1 FROM "Program" WHERE "id" = entry."id");
    target_slug := entry."slug";
    IF EXISTS (SELECT 1 FROM "Program" WHERE "organizationId" = org_id AND "slug" = target_slug) THEN
      target_slug := entry."slug" || '-suite';
      RAISE WARNING 'suite catalog import: slug % already used in nxt-lvl, imported as %', entry."slug", target_slug;
    END IF;
    INSERT INTO "Program" ("id", "organizationId", "name", "slug", "type", "status", "settings", "createdAt", "updatedAt")
    VALUES (entry."id", org_id, entry."name", target_slug, 'suite_app', entry."status", entry."settings", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;
"""
    open(target, "w").write(sql)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
